services:
    base:
        image: mongo
        volumes: 
            - ../data:/data/db
            - .:/app
        ports: 
            - 27017:27017
        # command:
        #     '--replSet rs0 --keyFile /data/db/keyfile --bind_ip base --dbpath /data/db'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: piu2h3rpun23rhbv
        healthcheck:
            test: ["CMD", "bash", "-c", "/app/healthcheck.sh"]
    node:
        build: 
            context: .
            dockerfile: ./run.Dockerfile
        volumes:
            - .:/app
        ports:
            - 3000:3000
        environment: 
            APP_DB_USER: app
            # the same as APP_PSSWD in the init service of init-db.docker-compose.yml
            APP_DB_PASS: asdij23rpokpkin43
            APP_DB_NAME: app
            NET_NAME: base

            SESSION_SECRET: poijn34g098h3g5n
        depends_on:
            base:
                condition: service_healthy